//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panda5
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public short orderid { get; set; }
        public short productid { get; set; }
        public float unitprice { get; set; }
        public short quantity { get; set; }
        public float discount { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
