//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panda5
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.order_details = new HashSet<order_details>();
        }
    
        public short productid { get; set; }
        public string productname { get; set; }
        public Nullable<short> supplierid { get; set; }
        public Nullable<short> categoryid { get; set; }
        public string quantityperunit { get; set; }
        public Nullable<float> unitprice { get; set; }
        public Nullable<short> unitsinstock { get; set; }
        public Nullable<short> unitsonorder { get; set; }
        public Nullable<short> reorderlevel { get; set; }
        public int discontinued { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
