//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panda5
{
    using System;
    using System.Collections.Generic;
    
    public partial class usstate
    {
        public short stateid { get; set; }
        public string statename { get; set; }
        public string stateabbr { get; set; }
        public string stateregion { get; set; }
    }
}
